backend:
  name: git-gateway
  repo: t0dorakis/clack-studio
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "project-post"
      - { label: "Title", name: "title", widget: "string", hint: please choose short titles}
      - { label: "Client", name: "client", widget: string }
      - { label: "Publish Date", name: "date", widget: "datetime", hint: the year will be shown in the description }
      - { label: "Shown in Barcode", name: "featuredproject", widget: "boolean", default: true }
      - { label: "Featured Image", name: "featuredimage", widget: image, hint: has to be 720x1080 pixel with a mximum size of 200kb (yes it is possible to have it even smaller and it still looks great), default: "/img/DoNotDeletePlaceholder.jpg" }
      - { label: "Centered first image", name: centeredFirstImage, widget: boolean, hint: give the start-image a padding, default: false }
      - { label: "Centered first Image on mobile", name: centeredFirstImageMobile, widget: boolean, hint: give the start-image a padding , default: false }
      - { label: "Centered last image", name: centeredLastImage, widget: boolean, hint: give the end-image a padding , default: false }
      - { label: "Centered last Image on mobile", name: centeredLastImageMobile, widget: boolean, hint: give the end-image a padding , default: false }
      - { label: featured Video, name: featuredVideo, choose_url: false, required: false, widget: file, hint: not more then 1mb!!! this is very dangerous as too many featured videos can make the website super slow with bad SEO, use only as a last resort on one or two projects, default: null}
      - {
          label: Additional data,
          hint: data rows for the description; e.g. "Photographer — Paul Wiegeand",
          name: additionalData,
          widget: list,
          required: false,
          fields: [
              { label: Title, name: title, widget: string },
              { label: Data, name: data, widget: string }
           ]
        }
      - {
            label: Section,
            name: section,
            widget: list,
            hint: Here you can add as many photos and videos as you would like,
            fields:
            [
              { label: Image, name: src, required: false, widget: image },
              { label: Alt Text, required: false, name: altText, widget: text, hint: helps SEO , default: "" },
              { label: centered first image, name: centeredFirst, required: false, widget: boolean, hint: give the first image a padding of 4% , default: false },
              { label: centered first image on mobile, name: centeredFirstMobile, required: false, widget: boolean, hint: also on mobile - give the first image a padding of 4% , default: false },
              { label: Align on the left, name: left, required: false, widget: boolean, hint: forces the image to the left side of the screen (does not matter for mobiel) , default: false },
              { label: Fullscreen, name: horizontal, required: false, widget: boolean, hint: use only with a horicontal image , default: false },
              { label: second image, name: secondImage, required: false, widget: image, hint: if you add an image here there will be two images in one row next to each other},
              { label: Second Alt Text, required: false, name: altTextSecond, widget: text, hint: helps SEO (only if two images are in this section) , default: "" },
              { label: centered second image, name: centeredSecond, required: false, widget: boolean, hint: give the second image a padding of 4% , default: false },
              { label: centered second image on mobile, name: centeredSecondMobile, required: false, widget: boolean, hint: also on mobile - give the second image a padding of 4% , default: false },
              { label: video, name: video, choose_url: false ,required: false, widget: file, hint: h.264 compression not more then 1 or 2mb; uses alttext1 },
              { label: Embedded Video Url, name: embeddedVideo, required: false, widget: string, hint: just copy and paste the youtube or vimeo url. It can only be displayed horizontally (filling two sides on desktop) },
            ]
          }
      - { label: "Optional Text", name: "body", required: false, widget: "markdown" }
      - { label: "Services", name: "tags", required: false, widget: "list", hint: add multiple by comma seperation, default: ["art direction"] }
      - { label: "Last Image", name: "lastImage", required: false, widget: image, hint: this is the last image on the left of the navigation; can also be empty }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", default: "contact via mail, phone or instagram" }
          - { label: "Body", name: "body", required: false, widget: "markdown" }
      - file: "src/pages/imprint/index.md"
        label: "Imprint"
        name: "imprint"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", default: "Clack Studio GbR Vertreten durch: Hélène Marie Camille Mohrbutter & Mana Zarindast" }
          - { label: "Body", name: "body", required: false, widget: "markdown" }
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", default: "clack studio is a berlin based creative agency founded by a female friends duo in 2021" }
          - { label: "Body", name: "body", required: false, widget: "markdown" }
          - {
              label: Contact Data,
              hint: data rows for contact; e.g. "Phone — 0278 883 948",
              name: contactData,
              widget: list,
              required: false,
              fields: [
                  { label: Title, name: title, widget: string },
                  { label: Data, name: data, widget: string }
              ]
            }
          - {
              label: Social Links,
              hint: data rows for platforms; e.g. "Instagram — @200kilo",
              name: socialLinks,
              widget: list,
              required: false,
              fields: [
                  { label: Title, name: title, widget: string },
                  { label: Name, name: name, widget: string },
                  { label: URL, name: url, widget: string }
              ]
            }
  - name: "dynamic pages"
    label: "Extra Pages"
    folder: "src/pages/dynamic-pages"
    create: true
    slug: '{{fslug}}'
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "about-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", required: false, widget: "markdown" }