backend:
  name: git-gateway
  repo: t0dorakis/clack-studio
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "project-post"
      - { label: "Title", name: "title", widget: "string", hint: please choose short titles}
      - { label: "Client", name: "client", widget: string }
      - { label: "Publish Date", name: "date", widget: "datetime", hint: the year will be shown in the description }
      - { label: "Shown in Barcode", name: "featuredproject", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image, hint: has to be 720x1080 pixel with a mximum size of 200kb (yes it is possible to have it even smaller and it still looks great) }
      - { label: "Featured Mobile Image", name: "featuredimageMobile", required: false, widget: image, hint: has to be 1080x720 pixel with a mximum size of 180kb (yes it is possible to have it even smaller and it still looks great)  }
      - { label: featured Video, name: featuredVideo, required: false, widget: file, hint: not more then 1mb!!! this is very dangerous as too many featured videos can make the website super slow with bad SEO, use only as a last resort on one or two projects}
      - {
          label: Additional data,
          hint: data rows for the description; e.g. "Photographer — Paul Wiegeand",
          name: additionalData,
          widget: list,
          required: false,
          fields: [
              { label: Title, name: title, widget: string },
              { label: Data, name: data, widget: string }
           ]
        }
      - {
            label: Section,
            name: section,
            widget: list,
            hint: Here ayou can add as many photos and videos as you would like,
            fields:
            [
              { label: Image, name: src, required: false, widget: image },
              { label: Second Alt Text, required: false, name: altTextSecond, widget: text, hint: helps SEO (only if two images are in this section) },
              { label: Align on the left, name: left, required: false, widget: boolean, hint: forces the image to the left side of the screen (does not matter for mobiel) },
              { label: Fullscreen, name: horizontal, required: false, widget: boolean, hint: use only with a horicontal image },
              { label: second image, name: secondImage, required: false, widget: image, hint: if you add an image here there will be two images in one row next to each other},
              { label: Alt Text, required: false, name: altText, widget: text, hint: helps SEO },
              { label: video, name: video, required: false, widget: file, hint: h.264 compression not more then 1 or 2mb; uses alttext1;},
            ]
          }
      - { label: "Optional Text", name: "body", required: false, widget: "markdown" }
      - { label: "Services", name: "tags", required: false, widget: "list", hint: add multiple by comma seperation, default: ["art direction"] }
      - { label: "Last Image", name: "lastImage", required: false, widget: image, hint: this is the last image on the left of the navigation; can also be empty }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", required: false, widget: "markdown" }
      - file: "src/pages/imprint/index.md"
        label: "Imprint"
        name: "imprint"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", required: false, widget: "markdown" }
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", required: false, widget: "markdown" }
          - {
              label: Contact Data,
              hint: data rows for contact; e.g. "Phone — 0278 883 948",
              name: contactData,
              widget: list,
              required: false,
              fields: [
                  { label: Title, name: title, widget: string },
                  { label: Data, name: data, widget: string }
              ]
            }
          - {
              label: Social Links,
              hint: data rows for platforms; e.g. "Instagram — @200kilo",
              name: socialLinks,
              widget: list,
              required: false,
              fields: [
                  { label: Title, name: title, widget: string },
                  { label: Name, name: name, widget: string },
                  { label: URL, name: url, widget: string }
              ]
            }


